name: Destroy AWS Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm infrastructure destruction'
        required: true
        type: string

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

jobs:
  destroy_infra:
    name: Destroy AWS Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Validate confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]; then
          echo "❌ Destruction not confirmed. You must type 'DESTROY' to proceed."
          exit 1
        fi
        echo "✅ Destruction confirmed. Proceeding..."

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      working-directory: ./terraform
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
          -backend-config="region=${{ secrets.AWS_REGION }}"

    - name: Terraform Destroy
      working-directory: ./terraform
      env:
        TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        TF_VAR_ssh_public_key: "placeholder-key" # Dummy key for destroy
      run: |
        echo "🗑️ Destroying infrastructure..."
        terraform destroy -auto-approve
        echo "✅ Infrastructure destroyed successfully!"

    - name: Cleanup confirmation
      run: |
        echo "🧹 Infrastructure cleanup completed!"
        echo "📝 Manual cleanup still required:"
        echo "   - Delete S3 bucket: ${{ secrets.TF_STATE_BUCKET }}"
        echo "   - Remove GitHub Secrets (if no longer needed)"
        echo "   - Verify all AWS resources are deleted in console"